vimeo/php-mysql-engine

- src/Processor/CreateProcessor.php
- src/Schema/Column/Varbinary.php
[varbinary](https://dev.mysql.com/doc/refman/8.0/en/binary-varbinary.html) is similar to [`Varchar`](https://github.com/vimeo/php-mysql-engine/blob/master/src/Schema/Column/Varchar.php) and [`Blob`](https://github.com/vimeo/php-mysql-engine/blob/master/src/Schema/Column/Blob.php).
> Add Varbinary column class

- composer.json
The project does not have a license declaration in it's `composer.json` which can lead to issues with automatic checking tools like `metasyntactical/composer-plugin-license-check`
The license file in the repository seems to be `MIT` so I've added that.
> Add license declaration to composer.json

- src/Parser/SQLParser.php
- src/Parser/TruncateParser.php
- tests/EndToEndTest.php
- tests/TruncateParseTest.php
- promote truncate to clause, that also allows to use lowercase form `truncate`
- add optional form `TRUNCATE TABLE <table name>`
- add check for invalid `$tokens` array at `TruncateParser::parse` (ex. empty array), this could be helpful for direct usage of `TruncateParser` class (I don't know who will ever need this, but this is the way things should be done)
- add unit tests for `TruncateParser` class
> feat(TruncateParser): update `TRUNCATE`

- src/DataIntegrity.php
using `var_export` is a bit overkill but should do the job
> fix(DataIntegrity): fix psalm error about concatenation of `string` and `mixed`

- src/FakePdoStatementTrait.php
- tests/EndToEndTest.php
Problem query `TRUNCATE 'db_name'.'table_name'` becomes `TRUNCATE 'connection-db-name'.'db_name.table_name'`, that also affects `DROP TABLE`.
Also fixed copy-paste issue in data-provider for Truncate-e2e unit-test.
> fix(Truncate/Drop): fix parsing of table-name

- src/FakePdoTrait.php
- tests/FakePdoTest.php
Implement [`PDO::quote()`](https://www.php.net/manual/en/pdo.quote.php).
We maintain [a SQL template engine](https://github.com/BaguettePHP/TetoSQL) that depends on escaping with `PDO::quote()`.
Currently we have this method in a class that inherits from `FakePdo`.
> Add PDO::quote() to FakePdoTrait

- src/FakePdoStatementTrait.php
- src/Parser/SQLParser.php
- src/Parser/ShowParser.php
- src/Processor/ShowIndexProcessor.php
- src/Query/ShowIndexQuery.php
- src/Schema/Index.php
- tests/ShowIndexParseTest.php
Implement [SHOW INDEX](https://dev.mysql.com/doc/refman/8.0/en/show-index.html) syntax.
Set null for columns that depend on unimplemented processing.
A value that is set to CreateIndex but not set to Index is set to null for the time being. Since `Index->$column` is a string array, it is necessary to change the type, and it was expected that the scale would increase.
> Supports SHOW INDEX syntax

- .github/workflows/phpunit.yml
- .github/workflows/psalm.yml
- composer.json
- psalm-baseline.xml
- src/Parser/SQLLexer.php
The CI for this project continues to fail since https://github.com/vimeo/php-mysql-engine/commit/144d67bd725e01ae9736e5632dc89cf9ffe87e0a, affecting #15 and #16.
These issues have been resolved in the latest version of Psalm, so updating the dependencies for this project will be successful.
> Fix CI configuration and update Psalm for development

- src/FakePdoStatementTrait.php
- tests/EndToEndTest.php
This PR adds support for `\PDO::FETCH_COLUMN` fetch style in `FakePdoStatementTrait::fetch`.
It fixes usage of `\Doctrine\DBAL\Connection::fetchOne`
> Add support for FETCH_COLUMN in fetch

- src/FakePdoStatementTrait.php
- src/FakePdoTrait.php
- src/Php7/FakePdo.php
PDO::ATTR_DEFAULT_FETCH_MODE is the key for setAttribute, not fetch_style. (https://www.php.net/manual/en/pdo.setattribute.php)
The default for fetch_style is PDO::FETCH_BOTH, so set it.
(https://www.php.net/manual/en/pdostatement.fetch.php)
And I made it possible to set DEFAULT_FETCH_MODE with setAttribute.
This allows we to omit the fetch argument.
> Set default fetch style

- src/Parser/CreateTableParser.php
- tests/CreateTableParseTest.php
- tests/fixtures/create_table.sql
```
CREATE TABLE `orders`
(
`id` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`user_id` INTEGER(11) UNSIGNED,
`price` INTEGER(11) UNSIGNED NOT NULL DEFAULT 0,
`created_on`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`modified_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
```
Notice Error...
`Notice Error: Uninitialized string offset: 0 in [/path/to/vendor/vimeo/php-mysql-engine/src/Parser/CreateTableParser.php, line 936]`
> create table default data for integer 

- src/Processor/Expression/FunctionEvaluator.php
- tests/EndToEndTest.php
MySQL function [ROUND()](https://dev.mysql.com/doc/refman/5.6/en/mathematical-functions.html#function_round) can take 1 or 2 arguments. Second argument defaults to 0 if not specified.
> Fix: MySQL function ROUND() can take 1 or 2 arguments.

- src/FakePdoStatementTrait.php
- src/FakePdoTrait.php
The library is written for exception error handling (which is fine), but if any code treats it as generic PDO and calls `errorInfo()` things fall apart:
1. Native PDO code barfs rather annoying `No error: PDO constructor was not called` warning, that isn't easy to work around.
2. The return is `null`, rather than supposed three fields array structure.
Since the any _real_ error would be an exception anyway, I stubbed the methods to hardcode a no-error state for anything that asks.
Not confident that is _the_ way to go about it, but don't have a better idea. Open to explore alternative takes if there are any pointers. :)
> Stub errorInfo() to prevent upstream issues

- src/FakePdoStatementTrait.php
- src/FakePdoTrait.php
- src/Processor/Expression/FunctionEvaluator.php
- tests/EndToEndTest.php
Adds 2 new methods to function evaluator, INET_ATON and INET_NTOA
https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_inet-aton
> Adds INET_ATON and INET_NTOA mysql methods

- src/Processor/Expression/FunctionEvaluator.php
Added basic support for `UNIX_TIMESTAMP()` function:
- without arguments: returns current timestamp
- with single argument: transforms string representation of date/datetime to timestamp
Things could be done:
- add some checks for invalid values/formats
- add support for timezones
- support for floating point type of return value
```
mysql> SELECT UNIX_TIMESTAMP('2015-11-13 10:20:19.012');
-> 1447431619.012
```
Docs for function - [MySQL 8.0 Reference Manual](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_unix-timestamp)
> feat(UNIX_TIMESTAMP): add basic support for UNIX_TIMESTAMP function

- src/FakePdoStatementTrait.php
- src/FakePdoTrait.php
- src/Php8/FakePdo.php
- src/Php8/FakePdoStatement.php
Make this library compatible with PHP 8.1
> Add #[\ReturnTypeWillChange] for PHP 8.1 support

- src/Processor/CreateProcessor.php
- src/Schema/Column/CharacterColumn.php
- tests/CreateTableParseTest.php
- tests/fixtures/create_table.sql
Fixes two problems with `CHARACTER SET` & `COLLATE`
1. Neither  `CHARACTER SET` or `COLLATE` would actually be set properly on the resulting table definitions.
1. Both `CHARACTER SET` & `COLLATE` would be required for the `CharacterColumn::getPhpCode` to include it in php code generation
* [According to the grammar][1], they can be used individually
Changes:
* `src/Processor/CreateProcessor.php` The change to `getTextDefinitionColumn` allows the values parsed from sql to be passed to `Column` generation functions.
* `src/Schema/Column/CharacterColumn.php` generate each function arg individually
Added an integration test to the create table parser just for an easy add (`CreateProcessor::getDefinitionColumn` is private)
[1]: https://dev.mysql.com/doc/refman/5.7/en/charset-column.html
cc …
> Fix field support for CHARACTER SET & COLLATE

- src/FakePdo.php
Given that there are different versions for php7 vs. php8, provide a convenience method for getting the right one rather than having to have switching logic in the calling code...
> Convenience Method for Instantiating the Right FakePDO

- src/Processor/Expression/BinaryOperatorEvaluator.php
- src/Processor/SelectProcessor.php
SelectProcessor.php expected the return value of `Evaluator` to be an array for the case where the expression is a `SubqueryExpression`, but `Evaluator` already ensures the value returned is the value of the column requested. Also removing assertion as it does nothing in a production environment and might be mistaken as a stopper to run the code.
BinaryOperatorEvaluator.php would blindly try to divide any right/left value by the other without checking for 0 first.
> Fix a few PHP 8 related issues

- src/FakePdoStatementTrait.php
- tests/EndToEndTest.php
We've overridden the default value to our magic -123, which normally works, but if someone passes in `PDO::FETCH_DEFAULT` manually the method can't recognize it and throw an unimplemented error. This just makes sure the default is interpretted the same as -123, better matching the standard.
Added an appropriate test as well.
> fix: correctly handle the default `::fetch` style for statements

- src/Php8/FakePdo.php
- tests/EndToEndTest.php
This is a copy of the changes from #15 (0e864b2), making the two versions of `FakePdo` behave the same WRT respecting `->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, *)`.
Made sure to add an appropriate test.
> fix: use default fetch mode for PHP8 PDO implementation

- src/Processor/CreateProcessor.php
Default character set for utf8 in mysql 8 has changed to utf8mb3 for which there is not entry in the character set map.
> add mysql 8 utf8 default charset to character set map.

- src/FakePdoStatementTrait.php
- tests/EndToEndTest.php
PDO::FETCH_DEFAULT arrived as of PHP v8.0.7.  For those still on 7.4 referring to it directly in the code causes it to break with an undefined constant.
This checks to make sure the constant exists before comparing against it.
> Make Sure PDO::FETCH_DEFAULT is Defined

- src/Processor/Processor.php
- tests/EndToEndTest.php
SELECT WITH OFFSET is broken:
```
<?php
declare(strict_types=1);
include __DIR__.'/../vendor/autoload.php';
$pdo = new \Vimeo\MysqlEngine\Php8\FakePdo('mysql:dbname=depo;host=localhost', 'user', 'password');
$pdo->query('CREATE TABLE `test` (`id` INT NOT NULL) ENGINE=innodb DEFAULT CHARSET=utf8');
$pdo->query('INSERT INTO `test`(`id`) VALUES (1), (2)');
$stmt = $pdo->query('SELECT * FROM `test` LIMIT 10');
var_dump($stmt->fetch());
/*
Correct:
array(2) {
["id"]=>
string(1) "1"
[0]=>
string(1) "1"
}
*/
$stmt = $pdo->query('SELECT * FROM `test` LIMIT 10 OFFSET 1');
var_dump($stmt->fetch());
/*
Expected:
array(2) {
["id"]=>
string(1) "2"
[0]=>
string(1) "2"
}
Actual:
bool(false)
*/
```
I added a test and a fix for it.
> Fix for SELECT with OFFSET

- src/Parser/FromParser.php
- tests/EndToEndTest.php
Ignore FORCE INDEX specified after JOIN.
Adjust pointers in `buildJoin()` because there was a discrepancy between JOIN and other pointers assumed when calling SQLParser::skipIndexHints.
If you have a better policy, please let us know.
> feat: Skip FORCE INDEX for JOIN

- .github/workflows/phpunit.yml
- .github/workflows/psalm.yml
Fixes workflows, since actions/cache@v2 is disabled 
Updates actions/cache@v2 => actions/cache@v4
> update workflows to use actions/cache@v4

- src/Query/Expression/BinaryOperatorExpression.php
- tests/EndToEndTest.php
**what's changed**
Update the `negate` function in BinaryOperatorExpression to negate the existing value. This allows expressions with double negative, such as `NOT (:gameboy IS NOT NULL)`, to negate correctly.
**Example**
Prior to the change, the following query will return count 16 because  `NOT ("gameboy" IS NOT NULL)` is evaluated to `TRUE` and making the whole WHERE clause always `TRUE`. The expression, `NOT ("gameboy" IS NOT NULL)` should be `FALSE` because if `"gameboy" IS NOT NULL` is true, then `NOT(TRUE)` is `FALSE`
```
$query = $pdo->prepare("SELECT COUNT(*) as 'count' FROM `video_game_characters` WHERE (:console IS NOT NULL AND `console` = :console) OR NOT (:console IS NOT NULL)");
$query->bindValue(':console', 'gameboy');
$query->execute();
```
After the change, the query …
> ensures double negative is evaluated correctly

- src/Processor/Expression/FunctionEvaluator.php
- tests/EndToEndTest.php
This PR addresses two evaluation issues in SQL functions:
1.  **SUM() Evaluation:** The change ensures that the `SUM()` function can correctly evaluate expressions (e.g., `SUM(a + b)`).
2.  **CONVERT_TZ() Null Handling:** A check has been added to the `CONVERT_TZ()` function to handle cases where a column expression is empty (`null`). This prevents a fatal error and ensures the function behaves gracefully when processing incomplete or missing data.
> fix: Resolve evaluation issues in SUM() and CONVERT_TZ() functions
